// Generated by CoffeeScript 1.6.3
  var path = require('path');

  module.exports = function(grunt) {
    'use strict';
    var buildDir, lcovInstrumentDir, lcovLibForTestsDir, lcovReportDir, srcLibForTestsDir;
    
    buildDir = './build/';
    lcovInstrumentDir = './build/instrument/';
    lcovReportDir = './build/coverage/';
    srcLibForTestsDir = path.resolve(__dirname, 'lib/');
    lcovLibForTestsDir = path.resolve(__dirname, lcovInstrumentDir, 'lib');

    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      clean: {
        coverage: [lcovInstrumentDir, lcovReportDir],
        all: buildDir
      },
      env: {
        "default": {
          LIB_FOR_TESTS_DIR: srcLibForTestsDir
        },
        coverage: {
          LIB_FOR_TESTS_DIR: lcovLibForTestsDir
        }
      },
      mochaTest: {
        options: {
          reporter: 'spec'
        },
        src: ['test/**/*.js', '!test/factories/**/*.js']
      },
      jshint: {
        options: {
          globals: {
            console: true,
            module: true
          }
        },
        uses_defaults: ['lib/**/*.js'],
        with_overrides: {
          options: {
            expr: true
          },
          files: {
            src: ['test/**/*.js']
          }
        }
      },
      watch: {
        files: ['Gruntfile.coffee', 'test/**/*.js', 'lib/**/*.js'],
        tasks: ['jshint', 'mochaTest']
      },
      instrument: {
        files: './lib/*.js',
        options: {
          basePath: lcovInstrumentDir
        }
      },
      storeCoverage: {
        options: {
          dir: lcovReportDir
        }
      },
      makeReport: {
        src: lcovReportDir + 'coverage.json',
        options: {
          reporters: {
            lcov: {
              dir: lcovReportDir
            },
            text: true
          }
        }
      },
      coverage: {
        options: {
          dir: lcovReportDir,
          root: '',
          thresholds: {
            'statements': 90,
            'branches': 90,
            'lines': 90,
            'functions': 90
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-env');
    grunt.loadNpmTasks('grunt-mocha-test');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-istanbul');
    grunt.loadNpmTasks('grunt-istanbul-coverage');
    grunt.loadNpmTasks('grunt-notify');
    grunt.registerTask('test', ['jshint', 'mochaTest']);
    grunt.registerTask('default', ['test']);
    grunt.registerTask('cover', ['clean:coverage', 'env:coverage', 'instrument', 'mochaTest', 'storeCoverage', 'makeReport', 'coverage']);
  };

